export const FEATURES = [
  { value: 'outdoor_seating', label: 'Outdoor Seating' },
  { value: 'ocean_view', label: 'Ocean View' },
  { value: 'waterfront', label: 'Waterfront' },
  { value: 'parking', label: 'Parking' },
  { value: 'wifi', label: 'WiFi' },
  { value: 'takeout', label: 'Takeout' },
  { value: 'delivery', label: 'Delivery' },
  { value: 'reservations', label: 'Reservations' },
  { value: 'family_friendly', label: 'Family Friendly' },
  { value: 'dog_friendly', label: 'Dog Friendly' },
  { value: 'romantic', label: 'Romantic' },
  { value: 'live_music', label: 'Live Music' },
  { value: 'full_bar', label: 'Full Bar' },
  { value: 'wine_bar', label: 'Wine Bar' },
  { value: 'happy_hour', label: 'Happy Hour' },
  { value: 'brunch', label: 'Brunch' },
  { value: 'late_night', label: 'Late Night' },
  { value: 'private_dining', label: 'Private Dining' },
  { value: 'catering', label: 'Catering' },
  { value: 'coffee', label: 'Coffee' },
];
